#!/usr/bin/env bash
#install and configure nginx web server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
