#!/usr/bin/env bash
# Configure nginx web server with custom response header

var=$(hostname)
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# shellcheck disable=SC2154
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

# run server
sudo service nginx start
