#!/usr/bin/env bash
# Script to install and configure HAproxy
sudo apt-get -y update
# Install HA Proxy
sudo apt-get -y install haproxy
# Enable to HA Proxy to start at boot
sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
 backend web-backend
	balance roundrobin
	server 1474-web-01 34.148.111.80:80 check
	server 1474-web-02 44.200.41.152:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
