#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.
# Requirements:
#       Displays FizzBuzz when the number is a multiple of 3 and 5
#       Displays Fizz when the number is multiple of 3
#       Displays Buzz when the number is a multiple of 5
#       Otherwise, displays the number
#       In a list format

i=1
while [ $i -lt 101 ]; 
    do
    module3=$((i % 3 ))
    module5=$((i % 5))

    if [ $module3 -eq 0 ] && [ $module5 -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $module3 -eq 0 ]
    then
        echo "Fizz"
    elif [ $module5 -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++ ))
done
