#!/usr/bin/env bash
# script that displays the visitor IP along with the HTTP 
#  and status code from the Apache log file with sorted manner.

path="./apache-access.log"
awk -F' ' '{print $1, $9}' "$path" | sort -n | uniq -c | sort -r
