#!/usr/bin/env bash
# prints Best School 10 times with condition
# condition is --> print Hi at the 9th iteration

i=1
while [ $i -le 10 ]
do
    if [ $i -ne 9 ]
    then
        echo "Best School"
    else
        echo "Hi"
    fi

    (( i++ ))
done
