#!/usr/bin/env bash
# Bash script that gives you information about the school file

a="$(pwd)/school"
if [ -e "$a" ]
then
    echo "school file exists"
    if [ -s "$a" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$a" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
